\version "2.22.0"

% \include "works/xxx/scores/full_score.ly"
% \include "works/xxx/scores/ob1.ly"
% \include "works/xxx/scores/ob2.ly"
% \include "works/xxx/scores/cor12.ly"
% \include "works/xxx/scores/ottoni.ly"
% \include "works/xxx/scores/vl1.ly"
% \include "works/xxx/scores/vl2.ly"
% \include "works/xxx/scores/vla.ly"
% \include "works/xxx/scores/soli.ly"
% \include "works/xxx/scores/coro.ly"
% \include "works/xxx/scores/org.ly"
% \include "works/xxx/scores/b.ly"
