\version "2.22.0"

tempoXXXIII = \tempoMarkup "Adagio"
tempoXXXIIIb = \tempoMarkup "Allegro"
tempoXXXIIIc = \tempoMarkup "Adagio"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
