\version "2.24.0"

tempoCLXXXIII = \tempoMarkup "Allegro moderato"
tempoCLXXXIIIb = \tempoMarkup "Adagio"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/vla.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
